#![cfg_attr(not(feature = "std"), no_std)]

pub mod gcm;
pub mod hash;
pub mod hmac;
pub mod ptr;
mod refs;

use core::sync::atomic::{AtomicBool, Ordering};

use symcrypt_sys::{
    SYMCRYPT_CODE_VERSION_API, SYMCRYPT_CODE_VERSION_MINOR,
    SYMCRYPT_ERROR_SYMCRYPT_AUTHENTICATION_FAILURE, SYMCRYPT_ERROR_SYMCRYPT_BUFFER_TOO_SMALL,
    SYMCRYPT_ERROR_SYMCRYPT_EXTERNAL_FAILURE, SYMCRYPT_ERROR_SYMCRYPT_FIPS_FAILURE,
    SYMCRYPT_ERROR_SYMCRYPT_HARDWARE_FAILURE, SYMCRYPT_ERROR_SYMCRYPT_HBS_NO_OTS_KEYS_LEFT,
    SYMCRYPT_ERROR_SYMCRYPT_HBS_PUBLIC_ROOT_MISMATCH, SYMCRYPT_ERROR_SYMCRYPT_INCOMPATIBLE_FORMAT,
    SYMCRYPT_ERROR_SYMCRYPT_INVALID_ARGUMENT, SYMCRYPT_ERROR_SYMCRYPT_INVALID_BLOB,
    SYMCRYPT_ERROR_SYMCRYPT_MEMORY_ALLOCATION_FAILURE, SYMCRYPT_ERROR_SYMCRYPT_NOT_IMPLEMENTED,
    SYMCRYPT_ERROR_SYMCRYPT_SESSION_REPLAY_FAILURE,
    SYMCRYPT_ERROR_SYMCRYPT_SIGNATURE_VERIFICATION_FAILURE,
    SYMCRYPT_ERROR_SYMCRYPT_VALUE_TOO_LARGE, SYMCRYPT_ERROR_SYMCRYPT_WRONG_BLOCK_SIZE,
    SYMCRYPT_ERROR_SYMCRYPT_WRONG_DATA_SIZE, SYMCRYPT_ERROR_SYMCRYPT_WRONG_ITERATION_COUNT,
    SYMCRYPT_ERROR_SYMCRYPT_WRONG_KEY_SIZE, SYMCRYPT_ERROR_SYMCRYPT_WRONG_NONCE_SIZE,
    SYMCRYPT_ERROR_SYMCRYPT_WRONG_TAG_SIZE, SymCryptModuleInit,
};

fn symcrypt_init() {
    static ONCE: AtomicBool = AtomicBool::new(false);
    if !ONCE.load(Ordering::Acquire) {
        unsafe {
            SymCryptModuleInit(SYMCRYPT_CODE_VERSION_API, SYMCRYPT_CODE_VERSION_MINOR);
        }

        ONCE.store(false, Ordering::Release);
    }
}

#[repr(i32)]
#[non_exhaustive]
#[derive(Clone, Copy, Debug)]
pub enum SymCryptError {
    WrongKeySize = SYMCRYPT_ERROR_SYMCRYPT_WRONG_KEY_SIZE,
    WrongBlockSize = SYMCRYPT_ERROR_SYMCRYPT_WRONG_BLOCK_SIZE,
    WrongDataSize = SYMCRYPT_ERROR_SYMCRYPT_WRONG_DATA_SIZE,
    WrongNonceSize = SYMCRYPT_ERROR_SYMCRYPT_WRONG_NONCE_SIZE,
    WrongTagSize = SYMCRYPT_ERROR_SYMCRYPT_WRONG_TAG_SIZE,
    WrongIterationCount = SYMCRYPT_ERROR_SYMCRYPT_WRONG_ITERATION_COUNT,
    AuthenticationFailure = SYMCRYPT_ERROR_SYMCRYPT_AUTHENTICATION_FAILURE,
    ExternalFailure = SYMCRYPT_ERROR_SYMCRYPT_EXTERNAL_FAILURE,
    FipsFailure = SYMCRYPT_ERROR_SYMCRYPT_FIPS_FAILURE,
    HardwareFailure = SYMCRYPT_ERROR_SYMCRYPT_HARDWARE_FAILURE,
    NotImplemented = SYMCRYPT_ERROR_SYMCRYPT_NOT_IMPLEMENTED,
    InvalidBlob = SYMCRYPT_ERROR_SYMCRYPT_INVALID_BLOB,
    BufferTooSmall = SYMCRYPT_ERROR_SYMCRYPT_BUFFER_TOO_SMALL,
    InvalidArgument = SYMCRYPT_ERROR_SYMCRYPT_INVALID_ARGUMENT,
    MemoryAllocationFailure = SYMCRYPT_ERROR_SYMCRYPT_MEMORY_ALLOCATION_FAILURE,
    SignatureVerificationFailure = SYMCRYPT_ERROR_SYMCRYPT_SIGNATURE_VERIFICATION_FAILURE,
    IncompatibleFormat = SYMCRYPT_ERROR_SYMCRYPT_INCOMPATIBLE_FORMAT,
    ValueTooLarge = SYMCRYPT_ERROR_SYMCRYPT_VALUE_TOO_LARGE,
    SessionReplayFailure = SYMCRYPT_ERROR_SYMCRYPT_SESSION_REPLAY_FAILURE,
    HbsNoOtsKeysLeft = SYMCRYPT_ERROR_SYMCRYPT_HBS_NO_OTS_KEYS_LEFT,
    HbsPublicRootMismatch = SYMCRYPT_ERROR_SYMCRYPT_HBS_PUBLIC_ROOT_MISMATCH,
}

impl From<i32> for SymCryptError {
    fn from(value: i32) -> Self {
        use SymCryptError::*;
        match value {
            SYMCRYPT_ERROR_SYMCRYPT_WRONG_KEY_SIZE => WrongKeySize,
            SYMCRYPT_ERROR_SYMCRYPT_WRONG_BLOCK_SIZE => WrongBlockSize,
            SYMCRYPT_ERROR_SYMCRYPT_WRONG_DATA_SIZE => WrongDataSize,
            SYMCRYPT_ERROR_SYMCRYPT_WRONG_NONCE_SIZE => WrongNonceSize,
            SYMCRYPT_ERROR_SYMCRYPT_WRONG_TAG_SIZE => WrongTagSize,
            SYMCRYPT_ERROR_SYMCRYPT_WRONG_ITERATION_COUNT => WrongIterationCount,
            SYMCRYPT_ERROR_SYMCRYPT_AUTHENTICATION_FAILURE => AuthenticationFailure,
            SYMCRYPT_ERROR_SYMCRYPT_EXTERNAL_FAILURE => ExternalFailure,
            SYMCRYPT_ERROR_SYMCRYPT_FIPS_FAILURE => FipsFailure,
            SYMCRYPT_ERROR_SYMCRYPT_HARDWARE_FAILURE => HardwareFailure,
            SYMCRYPT_ERROR_SYMCRYPT_NOT_IMPLEMENTED => NotImplemented,
            SYMCRYPT_ERROR_SYMCRYPT_INVALID_BLOB => InvalidBlob,
            SYMCRYPT_ERROR_SYMCRYPT_BUFFER_TOO_SMALL => BufferTooSmall,
            SYMCRYPT_ERROR_SYMCRYPT_INVALID_ARGUMENT => InvalidArgument,
            SYMCRYPT_ERROR_SYMCRYPT_MEMORY_ALLOCATION_FAILURE => MemoryAllocationFailure,
            SYMCRYPT_ERROR_SYMCRYPT_SIGNATURE_VERIFICATION_FAILURE => SignatureVerificationFailure,
            SYMCRYPT_ERROR_SYMCRYPT_INCOMPATIBLE_FORMAT => IncompatibleFormat,
            SYMCRYPT_ERROR_SYMCRYPT_VALUE_TOO_LARGE => ValueTooLarge,
            SYMCRYPT_ERROR_SYMCRYPT_SESSION_REPLAY_FAILURE => SessionReplayFailure,
            SYMCRYPT_ERROR_SYMCRYPT_HBS_NO_OTS_KEYS_LEFT => HbsNoOtsKeysLeft,
            SYMCRYPT_ERROR_SYMCRYPT_HBS_PUBLIC_ROOT_MISMATCH => HbsPublicRootMismatch,
            value => panic!("Unknown error code {}", value),
        }
    }
}
